export const SEARCH_TAGS = {
  dashboard: [
    "dashboard",
    "/",
    "timer",
    "time tracker",
    "time",
    "project",
    "current project",
    "notes",
    "team status",
    "status",
    "calendar",
    "holidays",
    "next holiday",
    "sessions",
    "home",
    "lobby",
  ],
  projects: ["project", "task", "work", "workspace"],
  about: ["about", "company", "about us"],
  taskManagement: [
    "task",
    "task management",
    "todo",
    "private",
    "done",
    "in progress",
    "work",
  ],
  leaveManagement: [
    "leave",
    "management",
    "leave management",
    "sick",
    "dont want to work",
    "no work",
    "work",
    "conflit risk",
  ],
  teams: [
    "teams",
    "workspaces",
    "peoples",
    "department",
    "members",
    "buddy",
    "buddies",
    "collegue",
    "friends",
    "workers",
  ],
  performance: [
    "system",
    "performance",
    "insights",
    "score",
    "acitivity",
    "tasks",
    "projects",
    "goals",
    "growth",
  ],
  finance: [
    "finance",
    "salary",
    "pay",
    "paycheck",
    "latest",
    "fun",
    "deposite",
    "card",
    "history",
    "money",
    "$",
    "dollar",
    "earnings",
    "happy happy happy",
    "currency",
  ],
  documents: ["document", "offer letter", "contract", "docs"],
  settings: [
    "settings",
    "profile",
    "professional",
    "preferences",
    "security",
    "passwords",
    "change password",
    "update password",
    "upload profile",
    "picture",
    "socials",
    "timezone",
    "change timezones",
    "currency",
    "change currency",
    "employee",
    "employment detail",
  ],
};
